#import "./PostFragment.gql"
mutation addPost($input: AddPostInput){
  addPost(data: $input) {
   message
   result { 
      ...Post 
   }
 }
}

# {
#   "input": { "title": "helloooo55555","body": "这是一个测试" }
# }